name: "Chromatic (push)"
on: [push]

jobs:
  chromatic:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: yarn
    - run: npx -p chromatic@6.0.2-canary.5 chromatic --project-token gcaw1ai2dgo --storybook-build-dir="storybook-static"
